name: Terminate Wav2lip All Models EC2 Spot Instance us-east-2

on:
  workflow_dispatch: # Manual trigger

env:
  AWS_REGION: us-east-2

jobs:
  terminate:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Retrieve IDs from SSM
        id: get_ids
        run: |
          INSTANCE_ID=$(aws ssm get-parameter --name "/sdxl/instance-id" --query "Parameter.Value" --output text 2>/dev/null || echo "")
          SPOT_REQ_ID=$(aws ssm get-parameter --name "/sdxl/spot-request-id" --query "Parameter.Value" --output text 2>/dev/null || echo "")
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
          echo "SPOT_REQ_ID=$SPOT_REQ_ID" >> $GITHUB_ENV

      - name: Cancel Spot request
        run: |
          if [ -n "$SPOT_REQ_ID" ] && [ "$SPOT_REQ_ID" != "None" ]; then
            aws ec2 cancel-spot-instance-requests --spot-instance-request-ids $SPOT_REQ_ID
            echo "✅ Spot request $SPOT_REQ_ID cancelled"
          else
            echo "No Spot request ID found in SSM"
          fi

      - name: Terminate EC2 instance
        run: |
          if [ -n "$INSTANCE_ID" ] && [ "$INSTANCE_ID" != "None" ]; then
            aws ec2 terminate-instances --instance-ids $INSTANCE_ID
            aws ec2 wait instance-terminated --instance-ids $INSTANCE_ID
            echo "✅ Instance $INSTANCE_ID terminated"
          else
            echo "No Instance ID found in SSM"
          fi

      - name: Delete SSM parameters
        run: |
          aws ssm delete-parameter --name "/sdxl/instance-id" || true
          aws ssm delete-parameter --name "/sdxl/spot-request-id" || true

      - name: Output termination summary
        run: |
          echo "=============================================="
          echo "✅ SDXL deployment cleanup complete"
          echo "Instance: $INSTANCE_ID"
          echo "Spot request: $SPOT_REQ_ID"
          echo "=============================================="
